name:                eta-prelude
version:             0.4.2
synopsis:            The Eta prelude
description:         Please see README.md
homepage:            https://github.com/typelead/eta
license:             BSD3
license-file:        LICENSE
author:              Nikita Tchayka
maintainer:          nikitatchayka@gmail.com
category:            Language

library:
  exposed-modules:    Eta
  default-extensions: NoImplicitPrelude
  dependencies:
    - base >= 4.8 && < 5
    - bytestring
    - transformers
  source-dirs:      src
